### ISSUE TITLE
Meeting Page

### ISSUE THREAD

**Issue by nanosch** [nextsolx/ratsinformationssystem#18]
The Meeting Page_ is a little more ticky page. It consists of:
a **Header Section** as well as a **tab section** which contains three tabs:
- Überblick (Overview)
- ~~Tagesordnung (Agenda)~~ (We will cover this in a separate issue since we need to solve some issues with the designer)
- Teilnehmer (participant)

**Find sketch screens [here](https://convideracom.sharepoint.com/:u:/s/NetsolX/Ea0WKgjlD55EpLreg_6kKHMBfCQi_3ZVr_suGIqJZovTow?e=jeDnKx)**

## Header Section

this is the simplest part since it's only the title to display.

![image](https://user-images.githubusercontent.com/209799/62762544-09910000-ba92-11e9-988e-4641efccf9d6.png)

## tab section

as already said the tab section concists of three parts:

![image](https://user-images.githubusercontent.com/209799/62762720-74dad200-ba92-11e9-9698-6014a6cd2e88.png)

### Überblick (Overview)

the overview just shows basic information from the Meeting.

![image](https://user-images.githubusercontent.com/209799/62763122-7953ba80-ba93-11e9-98fd-aa4141748e41.png)

### ~~Tagesordnung (Agenda)~~

> will be tackled in a seperate issue.

### Teilnehmer (participant)

> note: remove sort option for the moment. we only show and filter the list. we send all participants so filtering can be done in frontend.

![image](https://user-images.githubusercontent.com/209799/62763228-b8820b80-ba93-11e9-8ba3-c9c368dee557.png)

**Comment by krausweb** [comment]
Done, according to PR https://github.com/nextsolx/ratsinformationssystem/pull/22
