### ISSUE TITLE
Themen Pages - the Filter block functionality(FE/BE)

### ISSUE THREAD

**Issue by krausweb** [nextsolx/ratsinformationssystem#20]
- refactor the front-end functionality
- add the back-end functionality for catching the **district** and **postcode**, from a filter on the **New, Progress, Finished** theme pages

**Comment by krausweb** [comment]
@MBeckers please, 
add the missing back-end part

**Comment by MBeckers** [comment]
done added in:
/neue-themen
/aktualisiert-themen
/abgeschlossen-themen

**Comment by krausweb** [comment]
@MBeckers, please 
according to the Map task( https://github.com/nextsolx/ratsinformationssystem/issues/26 ) and additional functionality, need to add for the **filter** functionality
1) relationship district **to subdistrict** list (the method that returns a list of subdistrict when we select a district in the filter)
2) relationship subdistrict **to postcode** list
 
branch
feature/theme-list-filter

**Comment by krausweb** [comment]
Approved PR here https://github.com/nextsolx/ratsinformationssystem/pull/30
