### ISSUE TITLE
Themen Karte Page

### ISSUE THREAD

**Issue by nanosch** [nextsolx/ratsinformationssystem#26]
The Themen Map is displaying all districts of cologne and sorts the theme to the district, filters the Themen depending on the selected district, and dives into the map to give a good view on where the Thema is "happening".

> Mobile Screens are not ready yet

There is only one View, however this is filtering While using the Map.

### Overview (Nothing selected)
when you're fistly enter the page or clear the filter, you see the Map of Cologne, no District is selected.

![image](https://user-images.githubusercontent.com/209799/63150151-5894e300-c006-11e9-9791-f497ae301ff0.png)

### Selecting a District

When you select a district you see all Thmen of this District (Themen in diesem Bezirk).

![image](https://user-images.githubusercontent.com/209799/63150273-aad60400-c006-11e9-9632-71c916d8965c.png)

Each District consists several District parts which are categorized by an PLZ (Postalcode). when you have selected a District, the Filter Menu changes to the Postal Code Selection. 

![image](https://user-images.githubusercontent.com/209799/63150358-e1ac1a00-c006-11e9-9fbc-0aa4e2fdd51d.png)

Also When you've a selected district, you're able to navigate back with `zurück zur Viertelübersicht` (back to the district overview)

### Selecting a Postalcode

When you have the Postal Code selected, there is no way to dive futher into the Map. So The Menu only shows a back button `Zurück zur PLZ-Übersicht` (back to the postalcode overview).

The Map itself then it's filter for exectly this postalcode.

![image](https://user-images.githubusercontent.com/209799/63150479-29cb3c80-c007-11e9-8854-69d636335fe9.png)

**Comment by krausweb** [comment]
@MBeckers, please need
1) controller for the Map page
2) relationship district to subdistrict list (the method that returns a list of subdistrict when we select a district in the filter)
3) relationship subdistrict to postcode list
