### ISSUE TITLE
Map Geo Location - Research  - City Districts and Sub Districts

### ISSUE THREAD

**Issue by dclermont90** [nextsolx/ratsinformationssystem#48]
- to accurately display the districts and sub districts geo data needs to be collected to create a border and place markers

**Comment by dclermont90** [comment]
I made some research and found the geo data for the city of cologne in one of their sub pages.

Whole city border:
https://www.offenedaten-koeln.de/dataset/stadtgebiet-koeln
Json data:
https://geoportal.stadt-koeln.de/arcgis/rest/services/Stadtgebiet/MapServer/0/query?where=objectid+is+not+null&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=4326&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&f=pjson

City districts
https://www.offenedaten-koeln.de/dataset/stadtbezirke
Json data:
https://geoportal.stadt-koeln.de/arcgis/rest/services/Stadtgliederung_15/MapServer/0/query?where=objectid+is+not+null&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=4326&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&f=pjson

Sub districts:
https://www.offenedaten-koeln.de/dataset/stadtteile
Json data:
https://geoportal.stadt-koeln.de/arcgis/rest/services/Stadtgliederung_15/MapServer/1/query?where=objectid+is+not+null&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=4326&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&f=pjson

**Comment by krausweb** [comment]
Please, I need the Index location too

**Comment by krausweb** [comment]
@dclermont90 please, 
where can I found locations for the place of markers
?

There is only the "geometry" node for the polygon(area)

**Comment by dclermont90** [comment]
@krausweb i will do further research for the marker locations, but i think the geo data for the marker has to be set manually.

**Comment by dclermont90** [comment]
I added two types of formats for the geo data in case the usual (used for polygons) doesn't work.
city district markers:
Nippes:
50°58'17.7"N 6°57'26.5"E
50.971578, 6.957353

Rodenkirchen:
50°53'24.3"N 6°58'01.4"E
50.890075, 6.967055

Ehrenfeld:
50°57'48.3"N 6°53'49.4"E
50.963414, 6.897050

Lindenthal:
50°56'10.1"N 6°50'42.3"E
50.936124, 6.845074

Porz:
50°53'08.3"N 7°03'41.8"E
50.885638, 7.061605

Kalk:
50°56'13.8"N 7°00'30.7"E
50.937164, 7.008535

Mühlheim:
50°57'29.5"N 7°00'20.4"E
50.958194, 7.005672

Innenstadt:
50°56'22.9"N 6°57'20.0"E
50.939688, 6.955551

Chorweiler:
51°01'40.4"N 6°52'23.4"E
51.027890, 6.873158

I'm working on the sub districts.

**Comment by dclermont90** [comment]
Here is the data for the sub districts. The data contains sub-districts that are also normal districts like Ehrenfeld or Nippes. If there are any problems with the "duplicates", just use the sub-districts in these cases. If you have any further questions, let me know.

Godorf:
50°51'07.0"N 6°58'41.8"E
50.851931, 6.978290

Lövenich:
50°56'41.6"N 6°49'49.2"E
50.944885, 6.830345

Weiden:
50°56'08.2"N 6°49'58.2"E
50.935605, 6.832833

Junkersdorf:
50°55'42.9"N 6°52'02.9"E
50.928587, 6.867484

Widdersdorf:
50°57'47.0"N 6°50'19.1"E
50.963058, 6.838630

Vogelsang:
50°57'29.0"N 6°52'47.5"E
50.958067, 6.879861

Weidenpesch:
50°59'00.8"N 6°56'50.0"E
50.983561, 6.947215

Mauenheim:
50°58'25.4"N 6°56'44.9"E
50.973726, 6.945810

Marienburg:
50°53'47.2"N 6°58'31.1"E
50.896444, 6.975292

Bayenthal:
50°54'35.5"N 6°58'07.2"E
50.909868, 6.968669

Weiß:
50°52'50.0"N 7°02'18.0"E
50.880562, 7.038320

Hahnwald:
50°52'24.6"N 6°59'01.6"E
50.873495, 6.983777

Meschenich:
50°51'07.0"N 6°56'06.9"E
50.851950, 6.935237

Immendorf:
50°50'54.4"N 6°57'25.8"E
50.848435, 6.957167

Buchforst:
50°56'52.7"N 7°00'14.2"E
50.947969, 7.003946

Höhenberg:
50°56'38.5"N 7°01'42.0"E
50.944017, 7.028328

Vingst:
50°55'55.5"N 7°01'22.2"E
50.932075, 7.022838

Grengel:
50°52'41.7"N 7°07'25.9"E
50.878255, 7.123849

Elsdorf:
50°55'59.5"N 6°33'57.3"E
50.933200, 6.565911

Wahnheide:
50°51'54.5"N 7°06'26.4"E
50.865145, 7.107328

Wahn:
50°51'35.1"N 7°05'27.1"E
50.859750, 7.090846

Libur:
50°50'24.2"N 7°04'49.4"E
50.840051, 7.080388

Lind:
50°50'47.2"N 7°06'51.6"E
50.846456, 7.114319

Ensen:
50°53'49.5"N 7°02'39.6"E
50.897072, 7.044336

Eil:
50°54'14.1"N 7°06'21.2"E
50.903909, 7.105891

Raderthal:
50°53'34.5"N 6°57'19.0"E
50.892912, 6.955271

Raderberg:
50°54'41.3"N 6°57'29.6"E
50.911470, 6.958223

Rondorf:
50°52'35.5"N 6°56'19.0"E
50.876522, 6.938604

Holweide:
50°58'07.8"N 7°02'47.1"E
50.968843, 7.046405

Buchheim:
50°57'35.5"N 7°01'31.5"E
50.959855, 7.025405

Merheim:
50°56'54.0"N 7°02'53.6"E
50.948335, 7.048229

Neubrück:
50°56'03.5"N 7°03'34.8"E
50.934297, 7.059666

Ostheim:
50°55'46.0"N 7°02'25.1"E
50.929444, 7.040299

Westhoven:
50°54'14.7"N 7°00'56.4"E
50.904076, 7.015655

Bocklemünd/Mengenich:
50°58'22.1"N 6°51'36.8"E
50.972815, 6.860210

Dünnwald:
51°00'26.6"N 7°02'49.5"E
51.007400, 7.047093

Höhenhaus:
50°59'09.6"N 7°01'53.8"E
50.985987, 7.031613

Poll:
50°54'54.1"N 6°59'49.4"E
50.915014, 6.997068

Humboldt/Gremberg:
50°55'37.7"N 7°00'23.5"E
50.927150, 7.006540

Deutz:
50°56'13.6"N 6°58'53.3"E
50.937110, 6.981473

Bickendorf:
50°57'40.5"N 6°53'48.5"E
50.961247, 6.896793

Sürth:
50°51'54.3"N 7°00'32.3"E
50.865074, 7.008963

Rodenkirchen:
50°53'23.7"N 6°57'53.8"E
50.889902, 6.964941

Urbach:
50°52'59.7"N 7°05'05.1"E
50.883238, 7.084742

Niehl:
50°59'34.6"N 6°57'11.5"E
50.992941, 6.953191

Flittard:
51°00'19.4"N 6°59'39.6"E
51.005380, 6.994338

Dellbrück:
50°58'26.6"N 7°04'38.2"E
50.974056, 7.077286

Rath/Heumar:
50°55'18.7"N 7°05'24.2"E
50.921866, 7.090055

Brück:
50°56'37.9"N 7°04'36.7"E
50.943863, 7.076866

Altstadt/Nord:
50°56'23.9"N 6°57'15.0"E
50.939960, 6.954158

Neustadt/Süd:
50°55'21.3"N 6°56'41.5"E
50.922592, 6.944864

Müngersdorf:
50°56'14.6"N 6°51'58.7"E
50.937383, 6.866301

Roggendorf/Thenhoven:
51°02'46.4"N 6°49'52.7"E
51.046228, 6.831295

Zündorf:
50°51'52.3"N 7°02'43.2"E
50.864521, 7.045338

Langel:
50°50'31.6"N 7°00'14.3"E
50.842099, 7.003982

Zollstock:
50°54'02.9"N 6°56'15.3"E
50.900818, 6.937593

Porz:
50°53'02.5"N 7°03'53.1"E
50.884028, 7.064760

Altstadt/Süd:
50°55'47.3"N 6°57'15.5"E
50.929818, 6.954311

Neustadt/Nord:
50°56'58.4"N 6°56'17.5"E
50.949556, 6.938202

Kalk:
50°56'18.2"N 7°00'27.3"E
50.938388, 7.007583

Braunsfeld:
50°55'53.0"N 6°53'35.4"E
50.931385, 6.893160

Ossendorf:
50°58'50.1"N 6°53'36.1"E
50.980584, 6.893372

Neuehrenfeld:
50°57'30.7"N 6°55'20.3"E
50.958525, 6.922316

Esch/Auweiler:
51°00'13.1"N 6°51'22.8"E
51.003630, 6.856321

Pesch:
50°59'55.9"N 6°52'30.4"E
50.998847, 6.875101

Volkhoven/Weiler:
51°01'03.7"N 6°52'44.1"E
51.017703, 6.878904

Heimersdorf:
51°00'31.6"N 6°53'58.5"E
51.008768, 6.899589

Chorweiler:
51°01'34.3"N 6°54'11.2"E
51.026203, 6.903108

Seeberg:
51°00'55.2"N 6°54'50.1"E
51.015342, 6.913916

Lindweiler:
51°00'20.0"N 6°53'19.0"E
51.005565, 6.888615

Worringen:
51°03'13.6"N 6°52'43.8"E
51.053763, 6.878839

Riehl:
50°57'47.8"N 6°58'39.2"E
50.963268, 6.977555

Nippes:
50°57'58.4"N 6°57'38.6"E
50.966212, 6.960726

Lindenthal:
50°56'16.9"N 6°50'37.8"E
50.938037, 6.843829

Sülz:
50°54'46.3"N 6°54'59.7"E
50.912858, 6.916585

Klettenberg:
50°53'58.0"N 6°55'12.0"E
50.899443, 6.919987

Bilderstöckchen:
50°58'16.2"N 6°55'49.5"E
50.971159, 6.930411

Longerich:
50°59'45.9"N 6°54'45.3"E
50.996078, 6.912578

Gremberghoven:
50°54'35.2"N 7°02'60.0"E
50.909768, 7.049991

Ehrenfeld:
50°58'07.5"N 6°53'43.5"E
50.968743, 6.895426

Finkenberg:
50°53'47.9"N 7°03'43.0"E
50.896639, 7.061953

Merkenich:
51°01'47.8"N 6°56'47.3"E
51.029948, 6.946459

Fühlingen:
51°01'49.8"N 6°54'53.8"E
51.030487, 6.914953

Blumenberg:
51°02'07.6"N 6°53'27.2"E
51.035437, 6.890874

Stammheim:
50°59'13.9"N 6°59'39.6"E
50.987181, 6.994324

Mühlheim:
50°57'35.2"N 7°00'13.4"E
50.959767, 7.003722

**Comment by krausweb** [comment]
Resend from PR

The geodata for postcodes.
https://geoportal.stadt-koeln.de/arcgis/rest/services/Adresse_15/MapServer/1/query?where=objectid+is+not+null&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=4326&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&f=pjson

**Comment by krausweb** [comment]
Done during to #65
