### ISSUE TITLE
need backend for global search func

### ISSUE THREAD

**Issue by vnchenko** [nextsolx/ratsinformationssystem#55]
1. On input focus, I have to display popular options of searching. (need api query)
2. For the autocomplete: I send a string which is the part of the title (or another field) and return me possible options
3. For the searching: I need a backend, which returns me all the relevant content for the query string.

**Comment by MBeckers** [comment]
about 1-2: Needs to be skipped, as it was agreed that we dont store own data (thats why we skipped "Merkliste" as well)
about 3: Dominique can you provide this

**Comment by vnchenko** [comment]
Can you give me a full description of this searching? Step by step, because I don't know, what I have to do.

**Comment by vnchenko** [comment]
Also, what about this button in the right corner? On click, I have to redirect on another page or show more data? 
![image](https://user-images.githubusercontent.com/22894279/65755996-e04d3180-e11c-11e9-91df-d6e56ce2ef09.png)
