### ISSUE TITLE
need backend for the gremien links

### ISSUE THREAD

**Issue by vnchenko** [nextsolx/ratsinformationssystem#56]
http://localhost/gremien/5c07e8562c66dc3b523e8b31
On the bottom, you can see "Weiterführende Links". So, I need API, where I can get them
![image](https://user-images.githubusercontent.com/22894279/65752742-13d88d80-e116-11e9-8a9f-3236ae7f93e4.png)

**Comment by MBeckers** [comment]
until know we didnt found anything that could work there well.
Lets include some dummy data into GremienResource, that can be swapped later on, when we have proper data from external API.

**Comment by MBeckers** [comment]
@vnchenko i merge links in backend so we can connect frontend
