### ISSUE TITLE
Topic Map Marker 

### ISSUE THREAD

**Issue by dclermont90** [nextsolx/ratsinformationssystem#70]
Topic Marker are not getting displayed on the map in the specific district.
I created a specific database dump with 3 topics and locations that contain geodata in lindenthal.
They also contain post codes ( 50933 & 50858 ) for their specific region

[database_2019-10-21.sql.zip](https://github.com/nextsolx/ratsinformationssystem/files/3750942/database_2019-10-21.sql.zip)

**Comment by dclermont90** [comment]
I created a new dump that contains also the post coe outside of the geojson array.
But there is an issue that there are two different locations for certain data that needs to be worked out @MBeckers 

[database_2019-10-23.sql.zip](https://github.com/nextsolx/ratsinformationssystem/files/3760638/database_2019-10-23.sql.zip)

**Comment by krausweb** [comment]
Please, I need to clarify and more detail, we have different sights on this.
1) all behaviour for the Map, step by step, from Koln to postcodes(Koln->district->subdistrc->postcodes)
2) all type of main design elements on the map:
- area
- popup
- marker
which step contains it(area, popup, marker) and it doesn't.
3) dependency from topics and map steps, and which map step has topics.

**Comment by MBeckers** [comment]
okay when navigating through the map we loading for example:
http://project-ris.nextsolx.team/api/topics/?district=Innenstadt&page=1 
as ajax
or
http://project-ris.nextsolx.team/api/topics/?postalCode=50670&page=1
and these topic data sometimes respond with geoData

These topic points should be shown as marker on the map

Example:
I navigate to district Lindenthal
Backend responds with 2 Topics -> place them on map
Navigate to subdistrict Lindenthal
Backend responds with 2 Topics -> Remove all current topic markers on map -> place the 2 markers on map
Navigate to some Postalcode 
Backend respond with only 1 Topic -> remove all current topic markes on map -> place the 1 marker on the map.

**Comment by krausweb** [comment]
Clear, thanks

---

If anyone changes the format of data, please let me know, see screen with the navigation subdistrict bug
![navigation_subdistrict_bug](https://user-images.githubusercontent.com/4416590/67387304-4e133e80-f59f-11e9-996c-e333541223c0.png)

**Comment by MBeckers** [comment]
okay sure, i will talk to the team, not sure who changed this.

**Comment by krausweb** [comment]
Please, 
in the future add more details, before I start the task.
The Main is:
1) data which I need to use 
2) mapping(connections between the backend and frontend data)
Because without this, any task will do very slowly.
---

The task in progress.
I need to changes and implement the marker position on the map according to the "geo" node from the topic data(discussed with Dominique), see screenshot
![right_geo_node_from_theme](https://user-images.githubusercontent.com/4416590/67481230-48365f80-f66a-11e9-9c41-97da10443504.png)
