### ISSUE TITLE
Meetings Dates are partially in english

### ISSUE THREAD

**Issue by dclermont90** [nextsolx/ratsinformationssystem#75]
The meeting dates on the front page and on the meeting section are partially in english, please change them to german.
<img width="940" alt="Bildschirmfoto 2019-10-25 um 14 37 48" src="https://user-images.githubusercontent.com/16760712/67572151-e93e1c80-f735-11e9-95ef-a56a6f5c8970.png">
<img width="1119" alt="Bildschirmfoto 2019-10-25 um 14 38 46" src="https://user-images.githubusercontent.com/16760712/67572154-eb07e000-f735-11e9-9d89-3ededc8670de.png">

**Comment by krausweb** [comment]
Here need to update the server settings.
On the FF side, the settings were made early, see (locale('de') in the resources/views/calendar-list.blade.php:64)
