### ISSUE TITLE
Improve Project Google Audit Rating

### ISSUE THREAD

**Issue by dclermont90** [nextsolx/ratsinformationssystem#76]
The performance of the project needs to be optimized for the Google Audit System (see Screenshot below).
This has to be done as good as possible for all the main and sub pages without any changes to the design.

<img width="1266" alt="Bildschirmfoto 2019-10-30 um 14 51 09" src="https://user-images.githubusercontent.com/16760712/67863821-ec198280-fb24-11e9-9d17-4b6f95d80c42.png">

The Settings that are relevant are:
Devices:
- Desktop
- Mobile

Audits:
- Seo
- Accessibility
- Best practices

If you need or some information, you can ask yaroslav for some suggestions.

**Comment by MBeckers** [comment]
![image](https://user-images.githubusercontent.com/9606393/67864783-7ca49280-fb26-11e9-9454-822e3133e666.png)

this is an example for mobile result on main page.
But we need to check it for every page
